# Generated by Django 5.2.6 on 2026-06-05 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[('VALERIA', 'VALERIA'), ('INGRID', 'INGRID'), ('JUAN CARLOS', 'JUAN CARLOS'), ('ROSITA', 'ROSITA'), ('LEYDI', 'LEYDI'), ('CLAUDIA', 'CLAUDIA'), ('LUCIA', 'LUCIA'), ('GLADYS', 'GLADYS'), ('MILTON', 'MILTON')], max_length=50)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('numero_expediente', models.CharField(max_length=100, unique=True)),
                ('numero_registro_principal', models.CharField(max_length=100, unique=True)),
                ('numero_registro_adjunto', models.CharField(blank=True, max_length=100)),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Oficio'), ('MEMORANDO', 'Memorando'), ('PROVEIDO', 'Proveído'), ('DICTAMEN', 'Dictamen'), ('RESOLUCION', 'Resolución')], max_length=50)),
                ('numero_documento', models.CharField(blank=True, max_length=30)),
                ('asunto', models.TextField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('oficina_derivada', models.CharField(blank=True, max_length=150)),
                ('firmo_jefe', models.BooleanField(default=False)),
                ('link_drive', models.URLField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', '🟡 Pendiente de salida'), ('DERIVADO', '🟢 Derivado'), ('ARCHIVADO', '🔵 Archivado')], default='PENDIENTE', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_tipo_numero_documento')],
            },
        ),
        migrations.CreateModel(
            name='ReservaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=20)),
                ('autor', models.CharField(choices=[('VALERIA', 'VALERIA'), ('INGRID', 'INGRID'), ('JUAN CARLOS', 'JUAN CARLOS'), ('ROSITA', 'ROSITA'), ('LEYDI', 'LEYDI'), ('CLAUDIA', 'CLAUDIA'), ('LUCIA', 'LUCIA'), ('GLADYS', 'GLADYS'), ('MILTON', 'MILTON')], max_length=50)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
    ]
