# Generated by Django 5.2.6 on 2026-06-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('mes_registro', models.CharField(max_length=50)),
                ('numero_expediente', models.CharField(max_length=100)),
                ('numero_registro_principal', models.CharField(max_length=100)),
                ('numero_registro_adjunto', models.CharField(blank=True, max_length=100)),
                ('autor', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Oficio'), ('MEMORANDO', 'Memorando'), ('PROVEIDO', 'Proveído'), ('DICTAMEN', 'Dictamen'), ('RESOLUCION', 'Resolución'), ('OTRO', 'Otro')], max_length=50)),
                ('numero_documento', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('oficina_derivada', models.CharField(max_length=150)),
                ('firmo_jefe', models.BooleanField(default=False)),
                ('link_drive', models.URLField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
