# Generated by Django 5.2.6 on 2026-06-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='fecha_creacion',
            new_name='creado',
        ),
        migrations.AlterField(
            model_name='documento',
            name='mes_registro',
            field=models.CharField(max_length=30),
        ),
    ]
