# Generated by Django 5.2.6 on 2026-06-02 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_rename_fecha_creacion_documento_creado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='mes_registro',
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='oficina_derivada',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
