# Generated by Django 5.2.6 on 2026-06-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_remove_documento_mes_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', '🟡 Pendiente de salida'), ('DERIVADO', '🟢 Derivado'), ('ARCHIVADO', '🔵 Archivado')], default='PENDIENTE', max_length=20),
        ),
    ]
