# Generated by Django 6.0 on 2026-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero_expediente',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero_registro_principal',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
