# Generated by Django 6.0 on 2026-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_documento_numero_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
