# Generated by Django 5.2.6 on 2026-06-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('sede_filial', models.CharField(blank=True, max_length=100, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=150, null=True)),
                ('unidad_nivel_1', models.CharField(blank=True, max_length=150, null=True)),
                ('area_nivel_2', models.CharField(blank=True, max_length=150, null=True)),
                ('sub_area_nivel_3', models.CharField(blank=True, max_length=150, null=True)),
                ('nombre_ambiente', models.CharField(blank=True, max_length=150, null=True)),
                ('piso_nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_ubicacion', models.TextField(blank=True, null=True)),
                ('cod_inv_2025', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_patrimonial_conciliado', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=150, null=True)),
                ('s_1', models.CharField(blank=True, max_length=50, null=True)),
                ('e_2', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
