# Generated by Django 6.0.6 on 2026-06-13 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_patrimonial', '0002_alter_bieninventario_dni_and_more'),
        ('trabajadores', '0002_remove_trabajador_apellidos_remove_trabajador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bieninventario',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes', to='trabajadores.trabajador'),
        ),
    ]
