# Generated by Django 5.2.6 on 2026-06-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_patrimonial', '0003_bieninventario_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bieninventario',
            name='trabajador',
        ),
    ]
