# Generated by Django 6.0.6 on 2026-06-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='telefono',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='ambiente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='local',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='piso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sede',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sub_area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='unidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
