# Generated by Django 5.2.6 on 2026-06-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_remove_trabajador_apellidos_remove_trabajador_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
